spring:
  application:
    name: relaydesk-api
  datasource:
    url: jdbc:postgresql://localhost:5432/relaydesk
    username: relaydesk
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

rd:
  jwt:
    secret: "change_me_to_a_secure_256_bit_random_string_for_hs256_signing"
  approvals:
    required: 1
